### PR TITLE
Fixed sabotaged methods, tests passing locally

### PR DESCRIPTION
**Pull request by adhetzer**
"13. Review the Pull Request and merge the forked repository with the original repository"

### CODE REVIEW

**Review by whe1123 — APPROVED** [review]
Changes look good. Great work!

**Review by emeraldswag312 — APPROVED** [review]
Everything looks good. I approve of these changes.

**Review by umdjpratama — APPROVED** [review]
Looks good!

**Comment by amanthanvi** [comment]
Looks good!

**Review by amanthanvi — COMMENTED** [review]
Looks good

**Pull request merged**
